name: Hello World Integração Contínua!

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  OlaMundo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: DigaDiga
        run: echo Hello-world!
